#line 2 "UrlHandler.c"

#line 4 "UrlHandler.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer html_create_buffer
#define yy_delete_buffer html_delete_buffer
#define yy_flex_debug html_flex_debug
#define yy_init_buffer html_init_buffer
#define yy_flush_buffer html_flush_buffer
#define yy_load_buffer_state html_load_buffer_state
#define yy_switch_to_buffer html_switch_to_buffer
#define yyin htmlin
#define yyleng htmlleng
#define yylex htmllex
#define yylineno htmllineno
#define yyout htmlout
#define yyrestart htmlrestart
#define yytext htmltext
#define yywrap htmlwrap
#define yyalloc htmlalloc
#define yyrealloc htmlrealloc
#define yyfree htmlfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE htmlrestart(htmlin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int htmlleng;

extern FILE *htmlin, *htmlout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up htmltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up htmltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via htmlrestart()), so that the user can continue scanning by
	 * just pointing htmlin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when htmltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int htmlleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow htmlwrap()'s to do buffer switches
 * instead of setting up a fresh htmlin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void htmlrestart (FILE *input_file  );
void html_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE html_create_buffer (FILE *file,int size  );
void html_delete_buffer (YY_BUFFER_STATE b  );
void html_flush_buffer (YY_BUFFER_STATE b  );
void htmlpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void htmlpop_buffer_state (void );

static void htmlensure_buffer_stack (void );
static void html_load_buffer_state (void );
static void html_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER html_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE html_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE html_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE html_scan_bytes (yyconst char *bytes,int len  );

void *htmlalloc (yy_size_t  );
void *htmlrealloc (void *,yy_size_t  );
void htmlfree (void *  );

#define yy_new_buffer html_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        htmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            html_create_buffer(htmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        htmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            html_create_buffer(htmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define htmlwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *htmlin = (FILE *) 0, *htmlout = (FILE *) 0;

typedef int yy_state_type;

extern int htmllineno;

int htmllineno = 1;

extern char *htmltext;
#define yytext_ptr htmltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up htmltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	htmlleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 9
#define YY_END_OF_BUFFER 10
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[589] =
    {   0,
        0,    0,    5,    5,    6,    6,    7,    7,    0,    0,
       10,    8,    9,    4,    8,    5,    5,    5,    6,    6,
        6,    7,    7,    7,    0,    0,    0,    0,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    0,    0,    0,    0,    0,    0,    0,
        5,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    0,    0,    0,    0,    0,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    7,    7,    7,    7,
        7,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    0,    0,    0,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    5,    5,    5,    5,    5,    5,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    1,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    0,    0,    0,    1,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    5,
        5,    5,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    2,    6,    6,    6,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    2,    7,    7,    7,

        1,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        2,    0,    0,    0,    0,    0,    0,    2,    0,    0,
        0,    0,    0,    0,    0,    2,    5,    5,    5,    5,
        5,    5,    2,    5,    5,    5,    5,    5,    5,    5,
        2,    6,    6,    6,    6,    6,    6,    2,    6,    6,
        6,    6,    6,    6,    6,    2,    7,    7,    7,    7,
        7,    7,    2,    7,    7,    7,    7,    7,    7,    7,
        2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        1,    2,    0,    0,    0,    0,    0,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    2,    5,    5,

        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    1,    2,    6,    6,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    2,
        7,    7,    7,    7,    7,    0,    1,    0,    0,    0,
        0,    1,    0,    0,    0,    0,    0,    5,    1,    5,
        5,    5,    5,    1,    5,    5,    5,    5,    5,    6,
        1,    6,    6,    6,    6,    1,    6,    6,    6,    6,
        6,    7,    1,    7,    7,    7,    7,    1,    7,    7,
        7,    7,    7,    1,    0,    0,    0,    0,    0,    3,
        0,    0,    0,    2,    1,    5,    5,    5,    5,    5,

        3,    5,    5,    5,    2,    1,    6,    6,    6,    6,
        6,    3,    6,    6,    6,    2,    1,    7,    7,    7,
        7,    7,    3,    7,    7,    7,    2,    0,    0,    0,
        2,    3,    0,    2,    5,    5,    5,    2,    3,    5,
        2,    6,    6,    6,    2,    3,    6,    2,    7,    7,
        7,    2,    3,    7,    2,    0,    1,    2,    0,    5,
        1,    2,    5,    6,    1,    2,    6,    7,    1,    2,
        7,    1,    0,    3,    1,    5,    3,    1,    6,    3,
        1,    7,    3,    3,    3,    3,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    7,    1,    1,    8,    1,    9,    1,   10,   11,
       12,   13,   14,    1,    1,    1,   15,   16,   17,    1,
        1,   18,   19,   20,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   21,    1,   22,    1,

       23,   24,   25,   26,   27,    1,    1,    1,   28,   29,
       30,    1,    1,   31,   32,   33,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[34] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[628] =
    {   0,
        0,    4,    8,   12,   16,   20,   24,   28,   32,   36,
       75, 1998, 1998, 1998,   36,    0,    0,   60,    0,    0,
       84,    0,    0,  108,  128,  148,  168,   31,    0,  195,
      219,   25,   30,    0,  243,  267,   32,   37,    0,  291,
      315,   36,   39,  335,    0,   39,   52,   57,   59,   61,
      359,    0,   63,   76,   81,   79,   88,  383,    0,   84,
       84,   89,  100,  108,  407,    0,  104,  106,  110,  109,
      116,  112,  134,  133,  136,  427,  129,  140,  142,  150,
      456,  150,  160,  159,  158,  485,  159,  170,  175,  173,
      514,  176,  183,  539,  564,  584,  609,  180,  187,  187,

      193,  200,  638,  667,  691,  720,  195,  198,  210,  214,
      220,  749,  778,  802,  831,  218,  221,  219,  224,  242,
      860,  889,  913,  942,  238,  241,  241,  967,  257,    0,
        0,  256,  258,  262,  261,  987, 1007, 1027,  268,  266,
      288,  292, 1054,  300,    0,    0,  290,  290,  294,  293,
     1078, 1102,  308,  312,  313,  320,  325, 1126,  347,    0,
        0,  335,  337,  343,  348, 1150, 1174,  352,  360,  358,
      378,  383, 1198,  378,    0,    0,  376,  381,  385,  383,
     1222, 1246,  399,  402,  401,  411,  415,  417,    0,  433,
      431,  443,   76,  258,  425,  434,  449,  457,  464,  451,

      473,  463,    0,  100,  478,    0,  485,  483,  501,  120,
      516,  477,  501,  501,  512,  522,  509,  518,  517,    0,
      211,  527,    0,  539,  555,  559,  348,  576,  536,  547,
      564,  574,  592,  566,  581,  579,    0,  354,  591,    0,
      609,  625,  639,  419,  606,  584,  609,  612,  618,  646,
      627,  638,  645,    0,  556,  665,  667,  660,  689,  669,
      687,    0,  697,  692,  692, 1266, 1291,  710,  722,  699,
      726,  720,  734,  712,  732,    0,  748,  750,  743, 1320,
     1349,  763,  775,  765,  775,  779,  790,  752,  779,    0,
      805,  798,  794, 1378, 1407,  811,  815,  806,  831,  821,

      828,  821,  827,    0,  853,  853,  832, 1436, 1465,  863,
      873,  863,  885, 1490, 1515,  895,  896,  879, 1539,  831,
        0,  886,  888,  891,  897,  885,  911,  920, 1566, 1595,
      932,  908,  919, 1619,    0,    0,  921,  924,  932,  933,
      954,  961,  962, 1646, 1675,  979,  984,  996, 1699,    0,
        0,  943,  942,  964,  979,  999,  997, 1015, 1726, 1755,
     1039, 1001, 1019, 1779,    0,    0, 1008, 1010, 1021, 1028,
     1049, 1038, 1807,    0, 1041, 1044, 1046, 1051, 1052, 1070,
     1068, 1081, 1078, 1068, 1072, 1079, 1086, 1087, 1835,    0,
     1103, 1097, 1100, 1104, 1102, 1132, 1094, 1118, 1127, 1122,

     1126, 1134, 1151, 1153, 1863,    0, 1154, 1149, 1149, 1153,
     1166, 1142, 1166, 1186, 1194, 1166, 1173, 1180, 1185, 1199,
     1891,    0, 1205, 1198, 1200, 1214, 1214, 1214, 1231, 1234,
     1242, 1219, 1222, 1236, 1247, 1272, 1279, 1245, 1256, 1272,
     1282, 1292, 1297, 1293, 1293,    0, 1238, 1308, 1323, 1291,
     1306, 1313, 1324, 1332, 1334, 1328, 1333,    0, 1259, 1356,
     1363, 1333, 1348, 1362, 1366, 1346, 1374, 1376, 1376,    0,
     1283, 1392, 1403, 1382, 1399, 1404, 1408, 1390, 1429, 1406,
     1408,    0, 1421, 1439, 1426, 1434,    0, 1443, 1450, 1461,
     1460,    0, 1468, 1463, 1478, 1463, 1469,    0, 1493, 1499,

     1503, 1503,    0, 1507, 1491, 1540, 1504, 1513,    0, 1524,
     1549, 1542, 1548,    0, 1532, 1556, 1579, 1525, 1557,    0,
     1569, 1588, 1608, 1585,    0, 1583, 1592,    0, 1601, 1617,
     1621, 1629, 1610, 1639,    0, 1652, 1634, 1641, 1659, 1619,
     1649,    0, 1668, 1658, 1672, 1688, 1661, 1700,    0, 1703,
     1681, 1708, 1714, 1664, 1721, 1716, 1728, 1738, 1732, 1740,
     1745, 1751, 1754, 1758, 1767, 1769, 1759, 1772, 1780, 1782,
     1774, 1786, 1789, 1794, 1796, 1799, 1800, 1808, 1811, 1815,
     1817, 1819, 1823, 1827, 1829, 1831, 1836, 1998, 1921, 1924,
     1927, 1930, 1933,   50, 1935,    2, 1937,    0, 1939, 1941,

     1943, 1945, 1947, 1949, 1951, 1953, 1955, 1957, 1959, 1961,
     1963, 1965, 1967, 1969, 1971, 1973, 1975, 1977, 1979, 1981,
     1983, 1985, 1987, 1989, 1991, 1993, 1995
    } ;

static yyconst flex_int16_t yy_def[628] =
    {   0,
      589,  589,  590,  590,  591,  591,  592,  592,  589,  589,
      588,  588,  588,  588,  593,  594,  594,  595,  596,  596,
      597,  598,  598,  599,  593,  600,  593,   27,  594,  595,
      601,   30,   30,  596,  597,  602,   35,   35,  598,  599,
      603,   40,   40,  600,   44,   44,   44,   44,   27,   27,
      601,   51,   51,   51,   51,   30,   30,  602,   58,   58,
       58,   58,   35,   35,  603,   65,   65,   65,   65,   40,
       40,   44,   44,   44,   27,  604,   51,   51,   51,   30,
      605,   58,   58,   58,   35,  606,   65,   65,   65,   40,
      607,   44,   44,  608,  609,  604,  608,   96,   96,   96,

       51,   51,  610,  611,  605,  610,  105,  105,  105,   58,
       58,  612,  613,  606,  612,  114,  114,  114,   65,   65,
      614,  615,  607,  614,  123,  123,  123,  616,   44,   97,
       97,   97,   97,   97,   97,  609,  616,  609,  138,   96,
       96,   96,  617,   51,  106,  106,  106,  106,  106,  106,
      611,  617,  151,  151,  105,  105,  105,  618,   58,  115,
      115,  115,  115,  115,  115,  613,  618,  166,  166,  114,
      114,  114,  619,   65,  124,  124,  124,  124,  124,  124,
      615,  619,  181,  181,  123,  123,  123,  137,  137,  137,
      137,  137,   44,   44,   97,   97,   97,   97,  137,  138,

      138,   96,   96,   96,  152,  152,  152,  152,  152,   51,
       51,  106,  106,  106,  106,  152,  151,  151,  105,  105,
      105,  167,  167,  167,  167,  167,   58,   58,  115,  115,
      115,  115,  167,  166,  166,  114,  114,  114,  182,  182,
      182,  182,  182,   65,   65,  124,  124,  124,  124,  182,
      181,  181,  123,  123,  123,  137,  137,  137,   44,   97,
       97,   97,   97,  137,  138,  620,  620,   96,   96,  152,
      152,  152,   51,  106,  106,  106,  106,  152,  151,  621,
      621,  105,  105,  167,  167,  167,   58,  115,  115,  115,
      115,  167,  166,  622,  622,  114,  114,  182,  182,  182,

       65,  124,  124,  124,  124,  182,  181,  623,  623,  123,
      123,  137,  137,  624,  624,   97,   97,   97,  137,  138,
      267,  315,  267,  267,  267,   96,  152,  152,  625,  625,
      106,  106,  106,  152,  151,  281,  330,  281,  281,  281,
      105,  167,  167,  626,  626,  115,  115,  115,  167,  166,
      295,  345,  295,  295,  295,  114,  182,  182,  627,  627,
      124,  124,  124,  182,  181,  309,  360,  309,  309,  309,
      123,  137,  137,  315,  315,  315,  315,  315,  315,   97,
       97,   97,  137,  315,  267,  267,  267,  152,  152,  330,
      330,  330,  330,  330,  330,  106,  106,  106,  152,  330,

      281,  281,  281,  167,  167,  345,  345,  345,  345,  345,
      345,  115,  115,  115,  167,  345,  295,  295,  295,  182,
      182,  360,  360,  360,  360,  360,  360,  124,  124,  124,
      182,  360,  309,  309,  309,  137,  137,  315,  315,  315,
      315,   97,  137,  315,  267,  267,  267,  152,  152,  330,
      330,  330,  330,  106,  152,  330,  281,  281,  281,  167,
      167,  345,  345,  345,  345,  115,  167,  345,  295,  295,
      295,  182,  182,  360,  360,  360,  360,  124,  182,  360,
      309,  309,  309,  137,  315,  315,  315,  315,  137,  137,
      315,  267,  267,  267,  152,  330,  330,  330,  330,  152,

      152,  330,  281,  281,  281,  167,  345,  345,  345,  345,
      167,  167,  345,  295,  295,  295,  182,  360,  360,  360,
      360,  182,  182,  360,  309,  309,  309,  315,  315,  315,
      315,  137,  315,  267,  330,  330,  330,  330,  152,  330,
      281,  345,  345,  345,  345,  167,  345,  295,  360,  360,
      360,  360,  182,  360,  309,  315,  315,  315,  315,  330,
      330,  330,  330,  345,  345,  345,  345,  360,  360,  360,
      360,  315,  315,  315,  330,  330,  330,  345,  345,  345,
      360,  360,  360,  315,  330,  345,  360,    0,  588,  588,
      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,

      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588,  588,  588,  588,  588,  588,  588
    } ;

static yyconst flex_int16_t yy_nxt[2032] =
    {   0,
       39,   13,   34,   14,   15,   13,   14,   14,   15,   17,
       14,   14,   18,   17,   14,   14,   18,   20,   14,   14,
       21,   20,   14,   14,   21,   23,   14,   14,   24,   23,
       14,   14,   24,   13,   14,   14,   15,   13,   14,   14,
       15,   56,   14,   26,   57,   50,   27,   25,   63,   28,
       29,   64,   70,   71,   56,   72,   26,   57,   50,   27,
       25,   63,   28,   25,   64,   70,   71,   31,   72,   73,
       32,   74,   76,   33,  588,   25,   75,   25,  193,   77,
       31,  194,   73,   32,   74,   76,   33,   25,   25,   75,
       25,   36,   77,   78,   37,   79,   80,   38,  588,   81,

       82,   83,  268,   84,   36,  269,   78,   37,   79,   80,
       38,   25,   81,   82,   83,   41,   84,   85,   42,   86,
       87,   43,  210,   88,   89,  211,   90,   91,   41,   92,
       85,   42,   86,   87,   43,   26,   88,   89,   27,   90,
       91,   28,   92,   93,   94,  588,  101,  588,   26,  102,
       95,   27,   25,  103,   28,   45,   93,   94,   46,  101,
       47,   48,  102,   95,  104,   25,  103,  110,   45,  111,
      112,   46,  113,   47,   48,   26,  119,  104,   27,  120,
      110,   28,  111,  112,   49,  113,  121,  122,   26,  119,
      128,   27,  120,  129,   28,  588,  140,   49,   25,  121,

      122,  141,   31,  128,  142,   32,  129,  143,   33,  140,
      144,  155,  156,  282,  141,   31,  283,  142,   32,  588,
      143,   33,   44,  144,  155,  156,   52,  157,  158,   53,
      159,   54,   55,  588,  170,  171,  172,  588,  173,   52,
      157,  158,   53,  159,   54,   55,   25,  170,  171,  172,
       36,  173,  174,   37,  185,  186,   38,  588,  187,  193,
      259,  259,  194,   36,  588,  174,   37,  185,  186,   38,
       44,  187,  195,   72,   59,  196,  197,   60,  198,   61,
       62,  588,  201,  202,  136,  195,   72,   59,  196,  197,
       60,  198,   61,   62,   25,  201,  202,  136,   41,  203,

      204,   42,  210,  588,   43,  211,  212,  213,  214,  588,
      215,   41,  203,  204,   42,  588,   77,   43,   44,  212,
      213,  214,   66,  215,  217,   67,  218,   68,   69,   77,
      219,  220,  588,  221,  588,   66,  588,  217,   67,  218,
       68,   69,   45,  219,  220,   46,  221,   47,   48,  227,
      227,  229,  228,  228,  230,   45,  296,  231,   46,  297,
       47,   48,   44,   82,  229,  232,   52,  230,  234,   53,
      231,   54,   55,  588,  235,  236,   82,  588,  232,   52,
      244,  234,   53,  245,   54,   55,   44,  235,  236,  237,
       59,  238,  246,   60,   87,   61,   62,  588,  247,  248,

      249,  588,  237,   59,  238,  246,   60,   87,   61,   62,
       44,  247,  248,  249,   66,  251,  252,   67,  253,   68,
       69,  244,  254,  255,  245,  188,  588,   66,  251,  252,
       67,  253,   68,   69,   97,  254,  255,   98,  188,  188,
       99,  188,  260,  261,  588,  100,  588,   97,  257,  256,
       98,  188,  188,   99,  188,  260,  261,  258,  100,   96,
      262,  257,  256,  106,  188,  263,  107,  136,  265,  108,
      258,  588,  188,  262,  109,  588,  106,  267,  263,  107,
      136,  265,  108,  264,  266,  188,  205,  109,   96,  136,
      267,  205,  115,  205,  274,  116,  264,  266,  117,  205,

      271,  270,  136,  118,  205,  115,  205,  274,  116,  205,
      275,  117,  276,  271,  270,  272,  118,   96,  273,  259,
      277,  124,  205,  275,  125,  276,  279,  126,  272,  280,
      205,  281,  127,  277,  124,  222,  588,  125,  588,  279,
      126,  278,  280,  205,  281,  127,  131,  222,  222,  132,
      588,  133,  134,  288,  278,  284,  289,  135,  310,  131,
      222,  311,  132,  222,  133,  134,  288,  222,  284,  289,
      135,  137,  285,  286,  138,  290,  222,  139,  287,  259,
      222,  588,  291,  293,  137,  285,  286,  138,  290,  588,
      139,   97,  294,  295,   98,  291,  293,   99,  588,  239,

      222,  302,  100,  588,   97,  294,  295,   98,  301,  259,
       99,  292,  239,  222,  302,  100,  131,  239,  303,  132,
      588,  133,  134,  304,  292,  298,  305,  135,  588,  131,
      239,  303,  132,  239,  133,  134,  304,  588,  298,  305,
      135,  130,  299,  588,  307,  146,  239,  239,  147,  308,
      148,  149,  588,  300,  239,  299,  150,  307,  146,  309,
      239,  147,  308,  148,  149,  306,  300,  239,  188,  150,
      136,  314,  309,  188,  152,  188,  313,  153,  306,  588,
      154,  188,  312,  315,  314,  588,  188,  152,  188,  313,
      153,  259,  259,  154,   96,  312,  315,  316,  106,  317,

      188,  107,  318,  588,  108,  319,  320,  205,  136,  109,
      316,  106,  268,  188,  107,  269,  327,  108,  319,  320,
      205,  136,  109,  130,  326,  326,  330,  146,  205,  327,
      147,  329,  148,  149,  205,  328,  273,  259,  150,  330,
      146,  205,  331,  147,  329,  148,  149,  205,  328,  588,
      332,  150,  130,  333,  588,  331,  161,  335,  205,  162,
      588,  163,  164,  334,  588,  282,  345,  165,  283,  161,
      335,  205,  162,  222,  163,  164,  334,  341,  326,  345,
      165,  136,  342,  222,  343,  167,  222,  222,  168,  346,
      344,  169,  287,  259,  588,  342,  222,  343,  167,  588,

      222,  168,  346,  344,  169,   96,  222,  347,  350,  115,
      348,  349,  116,  296,  239,  117,  297,  356,  326,  222,
      118,  350,  115,  357,  349,  116,  588,  239,  117,  239,
      301,  259,  359,  118,  130,  360,  357,  361,  161,  239,
      358,  162,  239,  163,  164,  359,  365,  136,  360,  165,
      361,  161,  239,  358,  162,  362,  163,  164,  363,  365,
      136,  239,  165,  130,  588,  310,  364,  176,  311,  588,
      177,  188,  178,  179,  239,  371,  326,  372,  180,  364,
      176,  382,  382,  177,  188,  178,  179,  326,  326,  588,
      372,  180,  136,  188,  384,  373,  182,  380,  317,  183,

      381,  318,  184,  588,  385,  386,  188,  384,  373,  182,
      332,  195,  183,  333,  387,  184,   96,  385,  386,  205,
      124,  398,  382,  125,  195,  388,  126,  387,  205,  400,
      389,  127,  205,  124,  396,  588,  125,  397,  388,  126,
      401,  205,  400,  389,  127,  130,  402,  588,  212,  176,
      403,  416,  177,  401,  178,  179,  341,  326,  417,  402,
      180,  212,  176,  403,  416,  177,  588,  178,  179,  222,
      222,  417,  405,  180,  189,  404,  588,  190,  418,  191,
      192,  412,  222,  222,  413,  405,  347,  189,  404,  348,
      190,  418,  191,  192,  137,  229,  419,  138,  414,  382,

      139,  356,  326,  362,  588,  239,  363,  137,  229,  419,
      138,  420,  588,  139,  189,  199,  432,  190,  239,  191,
      192,  430,  382,  239,  420,  421,  433,  189,  199,  432,
      190,  588,  191,  192,  137,  434,  239,  138,  421,  433,
      139,  428,  588,  200,  429,  435,  188,  137,  434,  384,
      138,  371,  326,  139,  588,  246,  200,  188,  435,  188,
      438,  206,  384,  439,  207,  440,  208,  209,  246,  441,
      442,  442,  380,  438,  206,  381,  439,  207,  440,  208,
      209,  136,  441,  382,  382,  152,  188,  444,  153,  445,
      446,  154,  588,  443,  447,  205,  454,  442,  152,  188,

      444,  153,  445,  446,  154,  188,  443,  447,  205,  206,
      216,  400,  207,  450,  208,  209,  588,  451,  452,  453,
      398,  382,  206,  216,  400,  207,  450,  208,  209,  188,
      451,  452,  453,  223,  396,  205,  224,  397,  225,  226,
      588,  456,  455,  457,  412,  458,  223,  413,  205,  224,
      588,  225,  226,  136,  456,  455,  457,  167,  458,  459,
      168,  222,  416,  169,  588,  462,  463,  464,  466,  442,
      167,  588,  459,  168,  222,  416,  169,  188,  462,  463,
      464,  223,  233,  465,  224,  468,  225,  226,  414,  382,
      469,  470,  588,  471,  223,  233,  465,  224,  468,  225,

      226,  188,  222,  469,  470,  240,  471,  239,  241,  467,
      242,  243,  588,  432,  474,  222,  428,  475,  240,  429,
      239,  241,  467,  242,  243,  136,  432,  474,  476,  182,
      475,  477,  183,  478,  442,  184,  430,  382,  480,  481,
      493,  476,  182,  494,  477,  183,  588,  482,  184,  188,
      239,  480,  481,  240,  250,  483,  241,  479,  242,  243,
      482,  504,  485,  239,  505,  486,  240,  250,  483,  241,
      479,  242,  243,  322,  436,  485,  323,  437,  486,  324,
      188,  484,  484,  487,  325,  515,  322,  188,  516,  323,
      488,  588,  324,  188,  442,  442,  487,  325,  322,  489,

      188,  323,  490,  488,  324,  188,  491,  492,  496,  325,
      448,  322,  588,  449,  323,  497,  205,  324,  188,  491,
      492,  496,  325,  321,  498,  495,  484,  337,  497,  205,
      338,  205,  499,  339,  454,  442,  500,  498,  340,  501,
      337,  502,  205,  338,  205,  499,  339,  503,  466,  442,
      507,  340,  321,  588,  502,  205,  337,  508,  460,  338,
      503,  461,  339,  507,  222,  506,  484,  340,  588,  337,
      508,  222,  338,  509,  510,  339,  511,  222,  588,  512,
      340,  321,  222,  588,  222,  352,  509,  510,  353,  513,
      514,  354,  478,  442,  472,  222,  355,  473,  352,  518,

      239,  353,  513,  514,  354,  517,  484,  588,  519,  355,
      321,  239,  518,  239,  352,  520,  521,  353,  588,  524,
      354,  519,  525,  526,  239,  355,  527,  352,  520,  521,
      353,  522,  524,  354,  523,  525,  588,  239,  355,  321,
      528,  484,  484,  367,  529,  530,  368,  188,  531,  369,
      239,  588,  489,  528,  370,  490,  367,  529,  188,  368,
      188,  588,  369,  532,  532,  534,  534,  370,  321,  188,
      493,  188,  367,  494,  440,  368,  533,  535,  369,  536,
      495,  484,  188,  370,  588,  367,  205,  440,  368,  533,
      535,  369,  536,  541,  534,  537,  370,  375,  538,  205,

      376,  500,  377,  378,  501,  539,  532,  205,  379,  504,
      375,  205,  505,  376,  588,  377,  378,  452,  542,  540,
      205,  379,  375,  543,  205,  376,  544,  377,  378,  545,
      452,  542,  540,  379,  515,  375,  543,  516,  376,  549,
      377,  378,  506,  484,  546,  532,  379,  188,  222,  588,
      222,  511,  549,  258,  512,  383,  588,  222,  548,  534,
      188,  222,  464,  222,  547,  588,  258,  550,  383,  374,
      222,  551,  588,  391,  552,  464,  392,  547,  393,  394,
      550,  517,  484,  588,  395,  526,  391,  239,  527,  392,
      522,  393,  394,  523,  555,  534,  239,  395,  374,  476,

      239,  554,  391,  556,  588,  392,  557,  393,  394,  239,
      553,  532,  476,  395,  554,  391,  239,  438,  392,  530,
      393,  394,  531,  558,  558,  559,  395,  205,  588,  239,
      438,  532,  532,  272,  563,  399,  537,  188,  559,  538,
      205,  534,  534,  562,  558,  588,  272,  563,  399,  374,
      188,  541,  534,  407,  560,  588,  408,  561,  409,  410,
      544,  539,  532,  545,  411,  588,  407,  205,  450,  408,
      564,  409,  410,  565,  566,  558,  567,  411,  374,  571,
      205,  450,  407,  551,  462,  408,  552,  409,  410,  567,
      546,  532,  571,  411,  588,  407,  222,  462,  408,  588,

      409,  410,  548,  534,  588,  568,  411,  222,  569,  222,
      570,  558,  588,  286,  588,  415,  553,  532,  556,  474,
      222,  557,  239,  555,  534,  588,  286,  588,  415,  374,
      572,  572,  474,  423,  573,  239,  424,  574,  425,  426,
      558,  558,  560,  588,  427,  561,  423,  575,  572,  424,
      588,  425,  426,  562,  558,  588,  576,  427,  374,  577,
      564,  579,  423,  565,  580,  424,  588,  425,  426,  578,
      572,  566,  558,  427,  568,  423,  582,  569,  424,  583,
      425,  426,  581,  572,  570,  558,  427,  239,  572,  572,
      588,  573,  588,  300,  574,  431,  584,  584,  575,  572,

      239,  576,  585,  584,  577,  588,  300,  588,  431,  436,
      578,  572,  437,  579,  588,  188,  580,  586,  584,  581,
      572,  582,  588,  256,  583,  587,  584,  588,  188,  584,
      584,  585,  584,  586,  584,  588,  256,  448,  587,  584,
      449,  588,  588,  205,  588,  588,  588,  588,  588,  588,
      588,  270,  588,  588,  588,  588,  205,  588,  588,  588,
      588,  588,  588,  588,  270,  460,  588,  588,  461,  588,
      588,  222,  588,  588,  588,  588,  588,  588,  588,  284,
      588,  588,  588,  588,  222,  588,  588,  588,  588,  588,
      588,  588,  284,  472,  588,  588,  473,  588,  588,  239,

      588,  588,  588,  588,  588,  588,  588,  298,  588,  588,
      588,  588,  239,  588,  588,  588,  588,  588,  588,  588,
      298,   12,   12,   12,   16,   16,   16,   19,   19,   19,
       22,   22,   22,   25,   25,   30,   30,   35,   35,   40,
       40,   44,   44,   51,   51,   58,   58,   65,   65,   96,
       96,  105,  105,  114,  114,  123,  123,  130,  130,  136,
      136,  145,  145,  151,  151,  160,  160,  166,  166,  175,
      175,  181,  181,  188,  188,  205,  205,  222,  222,  239,
      239,  321,  321,  336,  336,  351,  351,  366,  366,  374,
      374,  390,  390,  406,  406,  422,  422,   11,  588,  588,

      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588
    } ;

static yyconst flex_int16_t yy_chk[2032] =
    {   0,
      598,    1,  596,    1,    1,    2,    1,    2,    2,    3,
        2,    3,    3,    4,    3,    4,    4,    5,    4,    5,
        5,    6,    5,    6,    6,    7,    6,    7,    7,    8,
        7,    8,    8,    9,    8,    9,    9,   10,    9,   10,
       10,   32,   10,   15,   33,   28,   15,   28,   37,   15,
      594,   38,   42,   43,   32,   46,   15,   33,   28,   15,
       28,   37,   15,   18,   38,   42,   43,   18,   46,   47,
       18,   48,   50,   18,   11,   49,   49,   50,  193,   53,
       18,  193,   47,   18,   48,   50,   18,   21,   49,   49,
       50,   21,   53,   54,   21,   55,   56,   21,    0,   57,

       60,   61,  204,   62,   21,  204,   54,   21,   55,   56,
       21,   24,   57,   60,   61,   24,   62,   63,   24,   64,
       67,   24,  210,   68,   69,  210,   70,   71,   24,   72,
       63,   24,   64,   67,   24,   25,   68,   69,   25,   70,
       71,   25,   72,   73,   74,    0,   77,    0,   25,   78,
       75,   25,   75,   79,   25,   26,   73,   74,   26,   77,
       26,   26,   78,   75,   80,   75,   79,   82,   26,   83,
       84,   26,   85,   26,   26,   27,   87,   80,   27,   88,
       82,   27,   83,   84,   27,   85,   89,   90,   27,   87,
       92,   27,   88,   93,   27,    0,   98,   27,   30,   89,

       90,   99,   30,   92,  100,   30,   93,  101,   30,   98,
      102,  107,  108,  221,   99,   30,  221,  100,   30,    0,
      101,   30,   31,  102,  107,  108,   31,  109,  110,   31,
      111,   31,   31,    0,  116,  117,  118,    0,  119,   31,
      109,  110,   31,  111,   31,   31,   35,  116,  117,  118,
       35,  119,  120,   35,  125,  126,   35,    0,  127,  129,
      194,  194,  129,   35,    0,  120,   35,  125,  126,   35,
       36,  127,  132,  129,   36,  133,  134,   36,  135,   36,
       36,    0,  139,  140,  139,  132,  129,   36,  133,  134,
       36,  135,   36,   36,   40,  139,  140,  139,   40,  141,

      142,   40,  144,    0,   40,  144,  147,  148,  149,    0,
      150,   40,  141,  142,   40,    0,  144,   40,   41,  147,
      148,  149,   41,  150,  153,   41,  154,   41,   41,  144,
      155,  156,    0,  157,    0,   41,    0,  153,   41,  154,
       41,   41,   44,  155,  156,   44,  157,   44,   44,  159,
      227,  162,  159,  227,  163,   44,  238,  164,   44,  238,
       44,   44,   51,  159,  162,  165,   51,  163,  168,   51,
      164,   51,   51,    0,  169,  170,  159,    0,  165,   51,
      174,  168,   51,  174,   51,   51,   58,  169,  170,  171,
       58,  172,  177,   58,  174,   58,   58,    0,  178,  179,

      180,    0,  171,   58,  172,  177,   58,  174,   58,   58,
       65,  178,  179,  180,   65,  183,  184,   65,  185,   65,
       65,  244,  186,  187,  244,  188,    0,   65,  183,  184,
       65,  185,   65,   65,   76,  186,  187,   76,  188,  191,
       76,  190,  195,  196,    0,   76,    0,   76,  191,  190,
       76,  192,  191,   76,  190,  195,  196,  192,   76,   81,
      197,  191,  190,   81,  192,  198,   81,  200,  200,   81,
      192,    0,  199,  197,   81,    0,   81,  202,  198,   81,
      200,  200,   81,  199,  201,  199,  205,   81,   86,  201,
      202,  208,   86,  207,  212,   86,  199,  201,   86,  205,

      208,  207,  201,   86,  208,   86,  207,  212,   86,  209,
      213,   86,  214,  208,  207,  209,   86,   91,  211,  211,
      215,   91,  209,  213,   91,  214,  217,   91,  209,  218,
      216,  219,   91,  215,   91,  222,    0,   91,    0,  217,
       91,  216,  218,  216,  219,   91,   94,  224,  222,   94,
        0,   94,   94,  229,  216,  224,  230,   94,  255,   94,
      224,  255,   94,  225,   94,   94,  229,  226,  224,  230,
       94,   95,  225,  226,   95,  231,  225,   95,  228,  228,
      226,    0,  232,  234,   95,  225,  226,   95,  231,    0,
       95,   96,  235,  236,   96,  232,  234,   96,    0,  239,

      233,  246,   96,    0,   96,  235,  236,   96,  245,  245,
       96,  233,  239,  233,  246,   96,   97,  241,  247,   97,
        0,   97,   97,  248,  233,  241,  249,   97,    0,   97,
      241,  247,   97,  242,   97,   97,  248,    0,  241,  249,
       97,  103,  242,    0,  251,  103,  242,  243,  103,  252,
      103,  103,    0,  243,  250,  242,  103,  251,  103,  253,
      243,  103,  252,  103,  103,  250,  243,  250,  258,  103,
      104,  258,  253,  256,  104,  257,  257,  104,  250,    0,
      104,  258,  256,  260,  258,    0,  256,  104,  257,  257,
      104,  259,  259,  104,  105,  256,  260,  261,  105,  263,

      264,  105,  263,    0,  105,  264,  265,  270,  265,  105,
      261,  105,  268,  264,  105,  268,  270,  105,  264,  265,
      270,  265,  105,  106,  269,  269,  274,  106,  272,  270,
      106,  272,  106,  106,  271,  271,  273,  273,  106,  274,
      106,  272,  275,  106,  272,  106,  106,  271,  271,    0,
      277,  106,  112,  277,    0,  275,  112,  279,  278,  112,
        0,  112,  112,  278,    0,  282,  288,  112,  282,  112,
      279,  278,  112,  284,  112,  112,  278,  283,  283,  288,
      112,  113,  284,  285,  285,  113,  284,  286,  113,  289,
      286,  113,  287,  287,    0,  284,  285,  285,  113,    0,

      286,  113,  289,  286,  113,  114,  292,  291,  293,  114,
      291,  292,  114,  296,  298,  114,  296,  297,  297,  292,
      114,  293,  114,  298,  292,  114,    0,  298,  114,  300,
      301,  301,  300,  114,  115,  302,  298,  303,  115,  299,
      299,  115,  300,  115,  115,  300,  307,  320,  302,  115,
      303,  115,  299,  299,  115,  305,  115,  115,  305,  307,
      320,  306,  115,  121,    0,  310,  306,  121,  310,    0,
      121,  312,  121,  121,  306,  311,  311,  312,  121,  306,
      121,  318,  318,  121,  312,  121,  121,  326,  326,    0,
      312,  121,  122,  313,  322,  313,  122,  316,  317,  122,

      316,  317,  122,    0,  323,  324,  313,  322,  313,  122,
      332,  316,  122,  332,  325,  122,  123,  323,  324,  327,
      123,  333,  333,  123,  316,  327,  123,  325,  328,  337,
      328,  123,  327,  123,  331,    0,  123,  331,  327,  123,
      338,  328,  337,  328,  123,  124,  339,    0,  331,  124,
      340,  352,  124,  338,  124,  124,  341,  341,  353,  339,
      124,  331,  124,  340,  352,  124,    0,  124,  124,  342,
      343,  353,  343,  124,  128,  342,    0,  128,  354,  128,
      128,  346,  342,  343,  346,  343,  347,  128,  342,  347,
      128,  354,  128,  128,  136,  346,  355,  136,  348,  348,

      136,  356,  356,  362,    0,  357,  362,  136,  346,  355,
      136,  357,    0,  136,  137,  137,  367,  137,  357,  137,
      137,  363,  363,  358,  357,  358,  368,  137,  137,  367,
      137,    0,  137,  137,  138,  369,  358,  138,  358,  368,
      138,  361,    0,  138,  361,  370,  372,  138,  369,  375,
      138,  371,  371,  138,    0,  361,  138,  143,  370,  372,
      376,  143,  375,  377,  143,  378,  143,  143,  361,  379,
      381,  381,  380,  376,  143,  380,  377,  143,  378,  143,
      143,  151,  379,  382,  382,  151,  383,  384,  151,  385,
      386,  151,    0,  383,  387,  388,  397,  397,  151,  383,

      384,  151,  385,  386,  151,  152,  383,  387,  388,  152,
      152,  391,  152,  392,  152,  152,    0,  393,  394,  395,
      398,  398,  152,  152,  391,  152,  392,  152,  152,  158,
      393,  394,  395,  158,  396,  399,  158,  396,  158,  158,
        0,  400,  399,  401,  412,  402,  158,  412,  399,  158,
        0,  158,  158,  166,  400,  399,  401,  166,  402,  403,
      166,  404,  407,  166,    0,  408,  409,  410,  413,  413,
      166,    0,  403,  166,  404,  407,  166,  167,  408,  409,
      410,  167,  167,  411,  167,  416,  167,  167,  414,  414,
      417,  418,    0,  419,  167,  167,  411,  167,  416,  167,

      167,  173,  415,  417,  418,  173,  419,  420,  173,  415,
      173,  173,    0,  423,  424,  415,  428,  425,  173,  428,
      420,  173,  415,  173,  173,  181,  423,  424,  426,  181,
      425,  427,  181,  429,  429,  181,  430,  430,  432,  433,
      447,  426,  181,  447,  427,  181,    0,  434,  181,  182,
      431,  432,  433,  182,  182,  435,  182,  431,  182,  182,
      434,  459,  438,  431,  459,  439,  182,  182,  435,  182,
      431,  182,  182,  266,  436,  438,  266,  436,  439,  266,
      436,  437,  437,  440,  266,  471,  266,  437,  471,  266,
      441,    0,  266,  436,  442,  442,  440,  266,  267,  443,

      437,  267,  443,  441,  267,  443,  444,  445,  450,  267,
      448,  267,    0,  448,  267,  451,  448,  267,  443,  444,
      445,  450,  267,  280,  452,  449,  449,  280,  451,  448,
      280,  449,  453,  280,  454,  454,  455,  452,  280,  455,
      280,  456,  455,  280,  449,  453,  280,  457,  466,  466,
      462,  280,  281,    0,  456,  455,  281,  463,  460,  281,
      457,  460,  281,  462,  460,  461,  461,  281,    0,  281,
      463,  461,  281,  464,  465,  281,  467,  460,    0,  467,
      281,  294,  467,    0,  461,  294,  464,  465,  294,  468,
      469,  294,  478,  478,  472,  467,  294,  472,  294,  474,

      472,  294,  468,  469,  294,  473,  473,    0,  475,  294,
      295,  473,  474,  472,  295,  476,  477,  295,    0,  480,
      295,  475,  481,  483,  473,  295,  483,  295,  476,  477,
      295,  479,  480,  295,  479,  481,    0,  479,  295,  308,
      485,  484,  484,  308,  486,  488,  308,  484,  488,  308,
      479,    0,  489,  485,  308,  489,  308,  486,  489,  308,
      484,    0,  308,  490,  490,  494,  494,  308,  309,  490,
      493,  489,  309,  493,  491,  309,  491,  496,  309,  497,
      495,  495,  490,  309,    0,  309,  495,  491,  309,  491,
      496,  309,  497,  505,  505,  499,  309,  314,  499,  495,

      314,  500,  314,  314,  500,  501,  501,  500,  314,  504,
      314,  501,  504,  314,    0,  314,  314,  502,  507,  502,
      500,  314,  315,  508,  501,  315,  510,  315,  315,  510,
      502,  507,  502,  315,  515,  315,  508,  515,  315,  518,
      315,  315,  506,  506,  512,  512,  315,  319,  506,    0,
      512,  511,  518,  319,  511,  319,    0,  511,  516,  516,
      319,  506,  513,  512,  513,    0,  319,  519,  319,  329,
      511,  521,    0,  329,  521,  513,  329,  513,  329,  329,
      519,  517,  517,    0,  329,  526,  329,  517,  526,  329,
      522,  329,  329,  522,  527,  527,  522,  329,  330,  524,

      517,  524,  330,  529,    0,  330,  529,  330,  330,  522,
      523,  523,  524,  330,  524,  330,  523,  529,  330,  530,
      330,  330,  530,  531,  531,  533,  330,  334,    0,  523,
      529,  532,  532,  334,  540,  334,  537,  532,  533,  537,
      334,  534,  534,  538,  538,    0,  334,  540,  334,  344,
      532,  541,  541,  344,  536,    0,  344,  536,  344,  344,
      544,  539,  539,  544,  344,    0,  344,  539,  536,  344,
      543,  344,  344,  543,  545,  545,  547,  344,  345,  554,
      539,  536,  345,  551,  543,  345,  551,  345,  345,  547,
      546,  546,  554,  345,    0,  345,  546,  543,  345,    0,

      345,  345,  548,  548,    0,  550,  345,  349,  550,  546,
      552,  552,    0,  349,    0,  349,  553,  553,  556,  550,
      349,  556,  553,  555,  555,    0,  349,    0,  349,  359,
      557,  557,  550,  359,  559,  553,  359,  559,  359,  359,
      558,  558,  560,    0,  359,  560,  359,  561,  561,  359,
        0,  359,  359,  562,  562,    0,  563,  359,  360,  563,
      564,  567,  360,  564,  567,  360,    0,  360,  360,  565,
      565,  566,  566,  360,  568,  360,  571,  568,  360,  571,
      360,  360,  569,  569,  570,  570,  360,  364,  572,  572,
        0,  573,    0,  364,  573,  364,  574,  574,  575,  575,

      364,  576,  577,  577,  576,    0,  364,    0,  364,  373,
      578,  578,  373,  579,    0,  373,  579,  580,  580,  581,
      581,  582,    0,  373,  582,  583,  583,    0,  373,  584,
      584,  585,  585,  586,  586,    0,  373,  389,  587,  587,
      389,    0,    0,  389,    0,    0,    0,    0,    0,    0,
        0,  389,    0,    0,    0,    0,  389,    0,    0,    0,
        0,    0,    0,    0,  389,  405,    0,    0,  405,    0,
        0,  405,    0,    0,    0,    0,    0,    0,    0,  405,
        0,    0,    0,    0,  405,    0,    0,    0,    0,    0,
        0,    0,  405,  421,    0,    0,  421,    0,    0,  421,

        0,    0,    0,    0,    0,    0,    0,  421,    0,    0,
        0,    0,  421,    0,    0,    0,    0,    0,    0,    0,
      421,  589,  589,  589,  590,  590,  590,  591,  591,  591,
      592,  592,  592,  593,  593,  595,  595,  597,  597,  599,
      599,  600,  600,  601,  601,  602,  602,  603,  603,  604,
      604,  605,  605,  606,  606,  607,  607,  608,  608,  609,
      609,  610,  610,  611,  611,  612,  612,  613,  613,  614,
      614,  615,  615,  616,  616,  617,  617,  618,  618,  619,
      619,  620,  620,  621,  621,  622,  622,  623,  623,  624,
      624,  625,  625,  626,  626,  627,  627,  588,  588,  588,

      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588,  588,  588,  588,  588,  588,  588,  588,  588,  588,
      588
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int html_flex_debug;
int html_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *htmltext;
#line 1 "UrlHandler.l"




#line 10 "UrlHandler.l"

/**
 * File: UrlHandler.l
 * --------------------
 * scan one html file and convert all its relative urls into absolute urls
 * and output the html
 * Update: Feb 2, 2005 by Zheyuan Yu
 */
 
#include "UrlHandler.h"
#include "assert.h"

// enable following define to show debug messages
#define D(x) //x;

/**
 * tags 
 */
#define URL 1
#define IMGURL 2
#define FORMURL 3
#define UNKNOWN 100

long htmlloc;


#line 1160 "UrlHandler.c"

#define INITIAL 0
#define begin_href 1
#define begin_img_href 2
#define begin_form_href 3
#define end_href 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int htmllex_destroy (void );

int htmlget_debug (void );

void htmlset_debug (int debug_flag  );

YY_EXTRA_TYPE htmlget_extra (void );

void htmlset_extra (YY_EXTRA_TYPE user_defined  );

FILE *htmlget_in (void );

void htmlset_in  (FILE * in_str  );

FILE *htmlget_out (void );

void htmlset_out  (FILE * out_str  );

int htmlget_leng (void );

char *htmlget_text (void );

int htmlget_lineno (void );

void htmlset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int htmlwrap (void );
#else
extern int htmlwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( htmltext, htmlleng, 1, htmlout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( htmlin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( htmlin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, htmlin))==0 && ferror(htmlin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(htmlin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int htmllex (void);

#define YY_DECL int htmllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after htmltext and htmlleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 44 "UrlHandler.l"

#line 1353 "UrlHandler.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! htmlin )
			htmlin = stdin;

		if ( ! htmlout )
			htmlout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			htmlensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				html_create_buffer(htmlin,YY_BUF_SIZE );
		}

		html_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of htmltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 589 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 588 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 45 "UrlHandler.l"
{ printf("%s",htmltext); BEGIN(begin_href); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 46 "UrlHandler.l"
{ printf("%s",htmltext); BEGIN(begin_img_href); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 47 "UrlHandler.l"
{ printf("%s",htmltext); BEGIN(begin_form_href); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "UrlHandler.l"
{ printf("%s",htmltext); BEGIN(end_href); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 49 "UrlHandler.l"
{ htmlloc += htmlleng; return URL; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 50 "UrlHandler.l"
{ htmlloc += htmlleng; return IMGURL; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 51 "UrlHandler.l"
{ htmlloc += htmlleng; return FORMURL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 52 "UrlHandler.l"
{ htmlloc += htmlleng; return UNKNOWN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "UrlHandler.l"
ECHO;
	YY_BREAK
#line 1483 "UrlHandler.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(begin_href):
case YY_STATE_EOF(begin_img_href):
case YY_STATE_EOF(begin_form_href):
case YY_STATE_EOF(end_href):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed htmlin at a new source and called
			 * htmllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = htmlin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( htmlwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * htmltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of htmllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					htmlrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			htmlrestart(htmlin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) htmlrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 589 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 589 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 588);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up htmltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					htmlrestart(htmlin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( htmlwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve htmltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void htmlrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        htmlensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            html_create_buffer(htmlin,YY_BUF_SIZE );
	}

	html_init_buffer(YY_CURRENT_BUFFER,input_file );
	html_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void html_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		htmlpop_buffer_state();
	 *		htmlpush_buffer_state(new_buffer);
     */
	htmlensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	html_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (htmlwrap()) processing, but the only time this flag
	 * is looked at is after htmlwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void html_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	htmlin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE html_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) htmlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in html_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) htmlalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in html_create_buffer()" );

	b->yy_is_our_buffer = 1;

	html_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with html_create_buffer()
 * 
 */
    void html_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		htmlfree((void *) b->yy_ch_buf  );

	htmlfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a htmlrestart() or at EOF.
 */
    static void html_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	html_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then html_init_buffer was _probably_
     * called from htmlrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void html_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		html_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void htmlpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	htmlensure_buffer_stack();

	/* This block is copied from html_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from html_switch_to_buffer. */
	html_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void htmlpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	html_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		html_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void htmlensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)htmlalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in htmlensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)htmlrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in htmlensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE html_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) htmlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in html_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	html_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to htmllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       html_scan_bytes() instead.
 */
YY_BUFFER_STATE html_scan_string (yyconst char * yystr )
{
    
	return html_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to htmllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE html_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) htmlalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in html_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = html_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in html_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up htmltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		htmltext[htmlleng] = (yy_hold_char); \
		(yy_c_buf_p) = htmltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		htmlleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int htmlget_lineno  (void)
{
        
    return htmllineno;
}

/** Get the input stream.
 * 
 */
FILE *htmlget_in  (void)
{
        return htmlin;
}

/** Get the output stream.
 * 
 */
FILE *htmlget_out  (void)
{
        return htmlout;
}

/** Get the length of the current token.
 * 
 */
int htmlget_leng  (void)
{
        return htmlleng;
}

/** Get the current token.
 * 
 */

char *htmlget_text  (void)
{
        return htmltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void htmlset_lineno (int  line_number )
{
    
    htmllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see html_switch_to_buffer
 */
void htmlset_in (FILE *  in_str )
{
        htmlin = in_str ;
}

void htmlset_out (FILE *  out_str )
{
        htmlout = out_str ;
}

int htmlget_debug  (void)
{
        return html_flex_debug;
}

void htmlset_debug (int  bdebug )
{
        html_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from htmllex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    htmlin = stdin;
    htmlout = stdout;
#else
    htmlin = (FILE *) 0;
    htmlout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * htmllex_init()
     */
    return 0;
}

/* htmllex_destroy is for both reentrant and non-reentrant scanners. */
int htmllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		html_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		htmlpop_buffer_state();
	}

	/* Destroy the stack itself. */
	htmlfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * htmllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *htmlalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *htmlrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void htmlfree (void * ptr )
{
	free( (char *) ptr );	/* see htmlrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 53 "UrlHandler.l"



/**
 * Converts and shows an relative url in absolute url format
 * linkUrl is url in the page of page_url
 * e.g. given page_url: http://www.google.com/about/address.html
 *         linkUrl: news.html
 *         will output http://www.goole.com/about/news.html
 *         if linkUrl: /new.html
 * @param linkUrl - an url in the page
 * @param pageUrl - url of the page
 * @param isGeoUrlAppended:  whether geo url appeded to the begin of extracted url: 0: no 1: yest
 */
void displayUrl (char* pageUrl, char* linkUrl, int isGeoUrlAppended) 
{
   int i, len = strlen(pageUrl);
   char* absolutePath = (char*)malloc(len+1);
   char* domainUrl = (char*)malloc(len+1);

   strcpy(absolutePath, pageUrl);
   strcpy(domainUrl, pageUrl);

   // get domain of given url
   // e.g.: given url http://www.google.com/about/address.html, will save http://www.google.com to domainUrl
   for (i=len; i>0; i--)
   {
      if (pageUrl[i] == '/') 
      {
         if (pageUrl[i-1] == '/' ) // is "//"
         {
            break;
         }
         else   // not "//"
         {
            domainUrl[i] = '\0';
         }
      }
   }
   
   /*if (strcmp(linkUrl, "/search")==0) {
   printf("\npageUrl: %s\n", pageUrl);
   printf("\ndomainUrl: %s\n", domainUrl);
   printf("\nlinkUrl: %s\n", linkUrl);
   }
   */
   
   // get absolutePath of given url
   //e.g.: given url http://www.google.com/about/address.html, will save http://www.google.com/about to absolutePath
   
   for (i=len; i>0; i--) 
   {
      if ( (pageUrl[i] == '/') && (pageUrl[i-1] != '/' ) ) 
      { // not "//"
         absolutePath[i] = '\0';
         break;
      }
   }
   
   if (isGeoUrlAppended == 1)
      printf("%s", GEO_URL);
      
   if (strncmp(linkUrl, "http", 4) == 0) //full absolute url
   {
      printf("%s", linkUrl);
   }
   else
   {
      if ( *linkUrl == '/' ) // relative url, root path
      {
         printf("%s%s", domainUrl, linkUrl);
      }
      else
      {
         printf("%s/%s", absolutePath, linkUrl);
      }
   }
    
   free(domainUrl);
   free(absolutePath);
}

/**
 * Process the url
 */
void processUrl(char* url)
{
   int tok;
   while ( (tok = htmllex()) ) {
      //printf("token: %s, tok: %d\n",htmltext);
      switch (tok) {
         case URL:
            //D ( printf("::processUrl url: %s\n<br>",htmltext); )
            displayUrl(url, htmltext, 1);
            break;
         case IMGURL:
            //D ( printf("::processUrl image url: %s\n<br>",htmltext); )
            displayUrl(url, htmltext, 0);
            break;
         case FORMURL:
            D ( printf("::processUrl form url: %s[end]\n",htmltext); )
            displayUrl(url, htmltext, 1);
            break;

         case UNKNOWN:
            //D( printf("::processUrl unknown url: %s",htmltext); )
            break;
         default:
            //D( printf("::processUrl other url: %s",htmltext); )
            break;
      }
    }
}

/**
 * Function: displayHtmlAbsoluteURL 
 * --------------------
 * scan html file and convert all relative url into absolute url path, by append given url to relative html
 * and output the html
 * Update: Feb 2, 2005 by Zheyuan Yu
 */

 void displayHtmlAbsoluteURL (char* html, char* url)
 {
   if (html) 
   {
      int len = strlen ( html );

      // give new string one extra byte for the flex scanner
      char * newHtml = (char*)malloc ( len + 2 );

      if ( newHtml )
      {
         memcpy ( newHtml, html, len + 1 );
      
         //append a '\0' to the end of string to make sure it is end with two '\0' for flex to scan
         newHtml[ len + 1 ] = '\0';

         YY_BUFFER_STATE buffer_state =html_scan_string (html);

         // process the url
         processUrl (url);

         html_delete_buffer(buffer_state);

         free ( newHtml );
      }

      
   }
   else
   {
      printf("out of memory when convert text to tokens!\n");
      exit(0);
   }
   
}

